### ISSUE TITLE
WidgetToolbarRepository could warn user if it gets empty array of items

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-widget#55]
Follow-up of https://github.com/ckeditor/ckeditor5-widget/pull/54.

For now, it might happen that the user will make a typo in the config and without any error, the toolbar will be visible as empty.

This warning could be inside the `WidgetToolbarRepository#register()` or inside every toolbar (the second approach would be slightly better as it could have the more meaningful message, e.g. `The "image.toolbar" config is undefined or an empty string. Please, make sure that your config doesn't contain a typo`.

**Comment by ma2ciek** [comment]
Recently I've made such a mistake. I've created the following config:

```
{
	media: {
		toolbar: [ 'comment' ],
	}
}
```

and I was surprised that the comment button doesn't show up. Finally, I've found that I have a typo and it should be `media` -> `mediaEmbed`.

**Comment by ma2ciek** [comment]
And I remember that there was some idea in the past to consume the editor configuration (or maybe there wasn't?). That would be super useful to have an information like:

```
The `config.media` wasn't consumed by any plugin. Probably you miss some plugin or you have a typo in the editor's configuration.
```

But that would require at least some small changes in every plugin that uses editor's config.

WDYT @Reinmar @pjasiun?

**Comment by pjasiun** [comment]
The idea is very nice (I do not remember it was suggested before), but as you mentioned we should change plugins to do it...

Or not. We can check if `config.get` was called on all configuration options and log configuration that was not get.

**Comment by ma2ciek** [comment]
Right, we can check `config.get` calls. But probably it would solve the problem only for one level deep since many plugins get their configuration namespace.

**Comment by ma2ciek** [comment]
I'll extract the idea to the ticket in the CKE5 since I think it could be quite nice and low costing.

**Comment by pjasiun** [comment]
:+1: But I think we should handle it in the next iteration when we will introduce debug mode.

**Comment by Reinmar** [comment]
I'm closing this because widget toolbar should not warn an error. Instead, it should make sure to not show the toolbar at all if it's empty. Why? Because a developer who's integrating CKEditor 5 with his app may want to hide some toolbar and then he/she should be able to configure it to `null` or whatever falsy value.

Passing a non-predefine (registered) config property to `Editor.create()` is a different story and https://github.com/ckeditor/ckeditor5/issues/1266 covers it perfectly.
