### ISSUE TITLE
Backspace/delete should be blocked if the editor is read only

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-widget#6]
Reported in https://github.com/ckeditor/ckeditor5-typing/issues/109.

Interestingly, if the widget feature extended the command instead of handling the feature, the problem would not exist, so it'd be worth checking if that's possible.

**Comment by pomek** [comment]
Could you explain the integration with the command a little bit more?

**Comment by Reinmar** [comment]
The backspace/delete support for widgets is implemented in `ckeditor5-widget/src/widget.js` and has nothing to do with the command. It listens on the view layer but it does not consider the editor status, which is the bug.

**Comment by szymonkups** [comment]
Some idea: command's `execute()` event is decorated. Maybe we can listen to that event (which will not be fired if command is disabled) instead of listening to delete key event?

**Comment by Reinmar** [comment]
This should work, but taken that the keydown listener handles 3 types of actions now (delete, select all, arrows) we need to fix the keydown listener anyway. 

In general, it would be good if this code plugged into the command.

But that's a too big task for this ticket.

**Comment by pomek** [comment]
Ok, so do we have some plan? Or should I fix the bug the easiest way?

**Comment by Reinmar** [comment]
> Or should I fix the bug the easiest way?

That's the plan – easiest *correct* way.
