### ISSUE TITLE
[Safari] Double-clicking around widgets with nested editable breaks selection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-widget#80]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

master

## 📋 Steps to reproduce

Use the nested editable manual test from ckeditor5-widget.

Double click at the end of the nested editable
![Kapture 2019-03-28 at 12 05 59](https://user-images.githubusercontent.com/1099479/55153122-f53b0f00-5151-11e9-9f06-878c37255ec9.gif)

Alternatively double click before a widget with a NE.

## ✅ Expected result

The selection should not cross the boundary of the widget.

## ❎ Actual result

The selection crosses the boundary of the widget.

## 📃 Other details that might be useful

A follow-up of https://github.com/ckeditor/ckeditor5/issues/1463.

**Comment by pomek** [comment]
```js
function shouldFixSelection( domEventData, view ) {
    if ( !env.isSafari ) {
        return false;
    }

    if ( domEventData.domEvent.detail == 2 && view.document.selection.getLastPosition().isAtEnd ) {
        return true;
    }

    if ( domEventData.domEvent.detail >= 3 ) {
        return true;
    }

    return false;
}
```

Use the function in order to check whether the selection should be updated in widget mousedown event handler. The code above fixes case inside the NE. Still need to figure out how to fix TC when you click before NE.

**Comment by Reinmar** [comment]
The selection is correctly set in the model and correctly rendered (in terms of its logical position in the DOM):

![image](https://user-images.githubusercontent.com/156149/55714285-ae230880-59f2-11e9-8031-ebb5ed7f281f.png)

The only problem here is that it's not entirely correct visually, but that's an upstream issue.
